blank_issues_enabled: false
contact_links:
  - name: ğŸš¨ Bug report
    url: https://cmty.app/nuxt/issues/new?type=bug-report&repo=example-auth0
    about: |
      Please report bugs here.
  - name: ğŸ™‹ Feature request
    url: https://cmty.app/nuxt/issues/new?type=feature-request&repo=example-auth0
    about: |
      Please request features here.
  - name: ğŸ¤” Consulting from the Nuxt team
    url: https://otechie.com/nuxt
    about: |
      Get technical support, project audits, app deployments, and custom development from the core Nuxt.js team.
  - name: â—ï¸ All other issues | å…¶ä»–é—®é¢˜
    url: https://cmty.app/nuxt/issues/new?repo=example-auth0
    about: |
      Please create all other issues here.
